### ISSUE TITLE
No release package for download

### ISSUE THREAD

**Issue by ghost** [finlaymacklon/pixi-tooltips#1]
Hi,

I am trying to follow the installation read me guide to download release package, but the release column is empty now.

And ZIP folder download link that show on readme is not working too.

**Comment by finlaymacklon** [comment]
Hi @siongwai thank you for letting me know! I will address that as soon as I can this week.

Once I've reuploaded the release package, I'll post another comment here to let you know. Thanks!

**Comment by finlaymacklon** [comment]
Hey @siongwai I have now uploaded the release zip file: [`pixi-tooltips-v0.0.2-alpha.zip`](https://github.com/finlaymacklon/pixi-tooltips/releases/pixi-tooltips-v0.0.2-alpha/).

You should be able to follow the same steps in the README as before. Please don't hesitate to reach out to me if you have any issues with loading the extension! Thank you

**Comment by ghost** [comment]
thank you very much. 

I will close this issue.
